---
# tasks file for ansible-role-docker-registry

- include_vars: "{{ ansible_os_family }}.yml"

- set_fact:
    docker_registry_hostname: "{{ hosts.infra[0].cname }}"
    docker_registry_instance_ip: "{{ hosts.infra[0].ip }}"

- name: "Run the registry container"
  include: docker-registry.yml
  when: inventory_hostname == docker_registry_hostname

